### ISSUE TITLE
KeyError: 'Description'

### ISSUE THREAD

**Issue by psteinb** [andikleen/pmu-tools#28]
Hi,
I just tried pmu-tools/ocerf.py on a haswell box:

```
$ ./ocperf.py
Traceback (most recent call last):
  File "./ocperf.py", line 774, in <module>
    emap = find_emap()
  File "./ocperf.py", line 599, in find_emap
    emap = json_with_extra(el)
  File "./ocperf.py", line 557, in json_with_extra
    add_extra_env(emap, el)
  File "./ocperf.py", line 574, in add_extra_env
    emap.add_uncore(uc)
  File "./ocperf.py", line 551, in add_uncore
    self.uncore_events[name] = UncoreEvent(name, row)
  File "./ocperf.py", line 241, in __init__
    e.desc = row['Description'].strip()
KeyError: 'Description'
```
it's trying to open `${HOME}/.cache//pmu-events/GenuineIntel-6-3F-uncore.json` which does not contain this field `Description` at any point.

Any ideas on how to proceed?
Best -

```
$ uname -a
Linux islay.mpi-cbg.de 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.1.1503 (Core) 
Release:        7.1.1503
Codename:       Core
$ cat /proc/cpuinfo|grep -i "name"|head -n1
model name      : Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz
```

**Comment by psteinb** [comment]
Sorry, I tried r103 with Haswell and this apparently didn't work. It works just fine with "master".
Friday afternoon ...

**Comment by andikleen** [comment]
Thanks. I created a new tag
