### ISSUE TITLE
NameError: global name 'sample_regs_user' is not defined

### ISSUE THREAD

**Issue by kula85** [andikleen/pmu-tools#34]
perf record -b --call-graph dwarf -- sleep 3
python perfdata.py perf.data

Traceback (most recent call last):
  File "/home/ubuntu/Source/pmu-tools/parser/perfdata.py", line 575, in <module>
    h = perf_file.parse_stream(f)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 197, in parse_stream
    return self._parse(stream, Container())
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 661, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 661, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 960, in _parse
    obj = self.subcon._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 287, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/lib/python2.7/dist-packages/construct/adapters.py", line 261, in _decode
    return self.inner_subcon._parse(BytesIO(obj), context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 519, in _parse
    obj.append(self.subcon._parse(stream, context))
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 659, in _parse
    sc._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 840, in _parse
    obj = self.cases.get(key, self.default)._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 270, in _parse
    return self.subcon._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 661, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 840, in _parse
    obj = self.cases.get(key, self.default)._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 661, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 430, in _parse
    count = self.countfunc(context)
  File "/home/ubuntu/Source/pmu-tools/parser/perfdata.py", line 127, in <lambda>
    Array(lambda ctx: sample_regs_user,
NameError: global name 'sample_regs_user' is not defined

**Comment by andikleen** [comment]
Fixed
