### ISSUE TITLE
Error parsing perf --version on master

### ISSUE THREAD

**Issue by keur** [andikleen/pmu-tools#391]
#### Trace

```
$ ~/repos/pmu-tools/toplev.py --core S0-C0 -l1 -v --no-desc taskset -c 0 ./a.out
Traceback (most recent call last):
  File "/home/keur/repos/pmu-tools/toplev.py", line 933, in <module>
    feat = PerfFeatures(args)
  File "/home/keur/repos/pmu-tools/toplev.py", line 283, in __init__
    perf_version = tuple(map(int, (v[2]).split(".")))[:2] if len(v) >= 3 else (0,0)
ValueError: invalid literal for int() with base 10: 'g7d2a07b76933'

$ perf --version
perf version 5.14.g7d2a07b76933
```

#### Other details
Checked out to `tags/r109` and it ran just fine.

**Comment by andikleen** [comment]
Thanks fixed.

This version check was more trouble than expected

**Comment by keur** [comment]
Thank you.

Kevin
