### ISSUE TITLE
ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by GreyGnome** [andikleen/pmu-tools#410]
I got this error just a few moments ago. I thought there wasn't any installation procedure or anything I needed to do besides run it. This is on a Fedora 35 laptop with an Intel  Core(TM) i7-6600U CPU.

[schwager@rodin2 perf]$ git clone https://github.com/andikleen/pmu-tools.git; cd pmu-tools
[schwager@rodin2 pmu-tools]$ ./ocperf
Downloading https://download.01.org/perfmon/mapfile.csv to mapfile.csv
Traceback (most recent call last):
  File "/home/schwager/Projects/perf/pmu-tools/./ocperf", line 1203, in <module>
    emap = find_emap(pmu=pmu.replace("/sys/devices/", ""))
  File "/home/schwager/Projects/perf/pmu-tools/./ocperf", line 979, in find_emap
    return json_with_extra(el, eventmap_is_file, pmu)
  File "/home/schwager/Projects/perf/pmu-tools/./ocperf", line 877, in json_with_extra
    name = event_download.eventlist_name(el, pmu_to_type[pmu])
  File "/home/schwager/Projects/perf/pmu-tools/event_download.py", line 232, in eventlist_name
    files = parse_map_file(name, key, acceptfile=True)
  File "/home/schwager/Projects/perf/pmu-tools/event_download.py", line 146, in parse_map_file
    cpu, version, name, typ = n
ValueError: too many values to unpack (expected 4)
[schwager@rodin2 pmu-tools]$ ./ocperf list
Traceback (most recent call last):
  File "/home/schwager/Projects/perf/pmu-tools/./ocperf", line 1203, in <module>
    emap = find_emap(pmu=pmu.replace("/sys/devices/", ""))
  File "/home/schwager/Projects/perf/pmu-tools/./ocperf", line 979, in find_emap
    return json_with_extra(el, eventmap_is_file, pmu)
  File "/home/schwager/Projects/perf/pmu-tools/./ocperf", line 877, in json_with_extra
    name = event_download.eventlist_name(el, pmu_to_type[pmu])
  File "/home/schwager/Projects/perf/pmu-tools/event_download.py", line 232, in eventlist_name
    files = parse_map_file(name, key, acceptfile=True)
  File "/home/schwager/Projects/perf/pmu-tools/event_download.py", line 146, in parse_map_file
    cpu, version, name, typ = n
ValueError: too many values to unpack (expected 4)

**Comment by dhschall** [comment]
#408 
I issued a pull request #411 but its not merged yet

**Comment by GreyGnome** [comment]
OK thanks.
